name: Noise2Noise tests

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  Noise2Noise-tests:

    runs-on:
      - self-hosted
      - Linux
      - X64

    steps:
    - uses: actions/checkout@v4

    - name: Check MLFlow
      run: |
        if [ "$(docker ps -q -f name=sacha-phd-mlflow)" ]; then
          echo "Container sacha-phd-mlflow is running."
        else
          echo "Container sacha-phd-mlflow is not running."
          exit 1
        fi

    - name: Check pytorch_parallelproj
      run: |
        if [ "$(docker ps -q -f name=sacha-phd-pytorch_parallelproj)" ]; then
          echo "Container sacha-phd-pytorch_parallelproj is running."
        else
          echo "Container sacha-phd-pytorch_parallelproj is not running."
          exit 1
        fi

    - name: Test with pytest
      run: |
          docker exec sacha-phd-pytorch_parallelproj bash -c "source /opt/conda/etc/profile.d/conda.sh && conda activate parallelproj_env && pytest --rootdir ${WORKSPACE}/noise2noise"